spring:
  main:    allow-bean-definition-overriding: true # 이미 등록된 bean을 override 하는 경우 발생하는 exception 해결
  cloud:
    stream:
      bindings:
        output-channel:
          destination: nerdy-bros-partition # 토픽 이름
          content-type: application/json
          producer:
            useNativeEncoding: true # 사용자 지정 Encoding 방식을 지정할 수 있는 설정
            partition-count: 3 # 해당 토픽 생기는 파티션 개수
        input-channel01: # 채널 이름
          destination: nerdy-bros-partition # 토픽 이름
          group: group01 # consumer group 이름
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
        input-channel02: # 채널 이름
          destination: nerdy-bros-partition # 토픽 이름
          group: group01 # consumer group 이름
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
        input-channel-other:
          destination: nerdy-bros-partition # 토픽 이름 
          group: otherGroup # consumer group 이름
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
      kafka:
        binder:
          auto-add-partitions: true
          producerProperties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer # key serialize 방식을 지정
            value.serializer: org.apache.kafka.common.serialization.StringSerializer # value serialize 방식을 지정
          consumerProperties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer # key deserialize 방식을 지정
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer # value deserialize 방식을 지정
          brokers:
          - localhost:9092 # 브로커 서버 설정