spring:
  main:
    allow-bean-definition-overriding: true # 이미 등록된 bean을 override 하는 경우 발생하는 exception 해결
  cloud:
    stream:
      bindings:
        output-channel:
          destination: nerdy-bros # 토픽 이름
          producer:
            use-native-encoding: true
        transactional-output-channel:
          destination: nerdy-bros # 토픽 이름
          producer:
            use-native-encoding: true
        input-channel:
          destination: nerdy-bros # 토픽 이름
          consumer:            use-native-decoding: true
      kafka:
        bindings:
          transactional-output-channel:
            producer:
              # idempotent producer 설정
              configuration:
                acks: all
                retries: 1000
                transactional.id: nerdyBros.
                enable:
                  # When set to 'true', the producer will ensure that exactly one copy of each message is written in the stream. 
                  # If 'false', producer retries due to broker failures, etc., may write duplicates of the retried message in the stream.
                  # Note that enabling idempotence requires max.in.flight.requests.per.connection to be less than or equal to 5
                  # retries to be greater than 0 and acks must be 'all'.
                  idempotence: true
          input-channel:
            consumer:              configuration:
                isolation:
                  level: read_committed
        binder:
          auto-create-topics: true
          auto-add-partitions: true
          producerProperties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer # key serialize 방식을 지정
            value.serializer: org.apache.kafka.common.serialization.StringSerializer # value serialize 방식을 지정
          brokers:
          - localhost:9092