spring:
  main:
    allow-bean-definition-overriding: true # 이미 등록된 bean을 override 하는 경우 발생하는 exception 해결
  cloud:
    stream:
      bindings:
        input-channel01: # 채널 이름
          destination: nerdy-bros # 토픽 이름
          group: consumerGroup01
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
        input-channel02: # 채널 이름
          destination: nerdy-bros # 토픽 이름
          group: consumerGroup02 # consumer group 이름
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
      kafka:
        binder:
          auto-add-partitions: true
          producerProperties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer # key serialize 방식을 지정
            value.serializer: org.apache.kafka.common.serialization.StringSerializer # value serialize 방식을 지정
          consumerProperties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer # key deserialize 방식을 지정
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer # value deserialize 방식을 지정
          brokers:
          - localhost:9092