spring:
  main:
    allow-bean-definition-overriding: true # 이미 등록된 bean을 override 하는 경우 발생하는 exception 해결
  cloud:
    stream:
      bindings:
        output-channel:
          destination: nerdy-bros # 토픽 이름
          producer:
            useNativeEncoding: true # 사용자 지정 Encoding 방식을 지정할 수 있는 설정
        auto-commit-input-channel: # 채널 이름
          destination: nerdy-bros # 토픽 이름
          group: autoCommitGroup # consumer group 이름
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
        non-auto-commit-input-channel: # 채널 이름
          destination: nerdy-bros # 토픽 이름
          group: nonAutoCommitGroup # consumer group 이름
          consumer:
            use-native-decoding: true # 사용자 지정 Decoding 방식을 지정할 수 있는 설정
      kafka:
        bindings:
          # https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/124, autoCommitOffset is different from enable.auto.commit
          # enable.auto.commit - the client(consumer) itself commits offset on a schedule, it relies on auto.commit.interval.ms.
          # autoCommitOffset - decide whether to commit or not by a container(consumer) when the container recieves a record from the broker
          auto-commit-input-channel:
            consumer:
              autoCommitOffset: true
          non-auto-commit-input-channel:
            consumer:
              autoCommitOffset: false
        binder:
          auto-create-topics: true
          auto-add-partitions: true
          producerProperties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer # key serialize 방식을 지정
            value.serializer: org.apache.kafka.common.serialization.StringSerializer # value serialize 방식을 지정
          consumerProperties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer # key deserialize 방식을 지정
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer # value deserialize 방식을 지정
          brokers:
          - localhost:9092 # 브로커 서버 설정