spring:
  cloud:
    stream:
      bindings:
        output-sync-channel: # 채널 이름
          destination: nerdy-bros # 토픽 이름
        output-async-channel: # 채널 이름
          destination: nerdy-bros # 토픽 이름
      kafka:
        binder:
          brokers:
          - localhost:9092
        bindings:
          output-async-channel:
            producer:
              configuration: 
                interceptor.classes: io.nerdybros.producer.ProducerWithCallback$CallBackInterceptor